spring.application.name=studentmanagement

# MySQL database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/student_management_db
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Manu@2810
server.port=8011

# JPA/Hibernate configuration for MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true